name: Advancedautotrain
version: '${version}'
main: io.github.yuku1a.advancedautotrain.Advancedautotrain
api-version: 1.19
depend: [ Train_Carts, SignLink]
commands:
  cslt:
    aliases: [cslt]
    usage: /<command> <action> <arguments...>
  optimer:
    aliases: [optimer]
    usage: /<command> <action> <arguments...>
  ar:
    aliases: [ar]
    usage: /<command> <action> <arguments...>
  lspawn:
    aliases: [ lspawn, lspn ]
    usage: /<command> <action> <arguments...>
  tpreset:
    aliases: [tpreset]
    usage: /<command> <action> <arguments...>
  trec:
    aliases: [trec]
    usage: /<command> <action> <arguments...>
  tal:
    aliases: [tal]
    usage: /<command> <action> <arguments...>
  aatdump:
    aliases: [aatdump]
    usage: /<command> <action> <arguments...>
  cstationcache:
    aliases: [cstationcache]
    usage: /<command> <action> <arguments...>
permissions:
  advancedautotrain.*:
    default: false
    children:
      advancedautotrain.admin: true
  advancedautotrain.admin:
    default: op
    children:
      advancedautotrain.use: true
  advancedautotrain.use:
    default: op